version: "3.7"

services: 
  database_ignite: 
    image: postgres
    container_name: database_ignite
    restart: always
  app:
    build: .
    container_name: rentx
    ports: 
      - 3333:3333 
    volumes: 
      - .:/usr/app
